import { Injectable } from "@nestjs/common";
import PDFDocument from "pdfkit";
import type { Quotation, QuotationLineItem, Vendor } from "@prisma/client";

type QuotationWithRelations = Quotation & {
  lineItems: QuotationLineItem[];
  vendor: Vendor;
};

@Injectable()
export class PdfService {
  generate(quotation: QuotationWithRelations): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50, size: "A4" });
      const chunks: Buffer[] = [];

      doc.on("data", (chunk: Buffer) => chunks.push(chunk));
      doc.on("end", () => resolve(Buffer.concat(chunks)));
      doc.on("error", reject);

      this.buildDocument(doc, quotation);
      doc.end();
    });
  }

  private buildDocument(doc: PDFKit.PDFDocument, q: QuotationWithRelations): void {
    const { vendor } = q;
    const blue = "#1d4ed8";
    const grey = "#6b7280";
    const black = "#111827";
    const lightGrey = "#f3f4f6";

    // Header
    doc.fontSize(22).fillColor(blue).text("FULFILUS", 50, 50);
    doc.fontSize(9).fillColor(grey).text("Vendor Intelligence Platform", 50, 76);
    doc.fontSize(9).fillColor(black)
      .text(`Date: ${new Date().toLocaleDateString("en-IN")}`, 400, 50, { align: "right" })
      .text(`Ref: ${q.referenceNumber}`, 400, 64, { align: "right" });

    doc.moveTo(50, 96).lineTo(545, 96).strokeColor("#d1d5db").stroke();

    // Quotation type banner
    const typeLabel = q.type === "RFQ" ? "REQUEST FOR QUOTATION"
      : q.type === "PRICE_LIST" ? "VENDOR PRICE LIST"
      : "PURCHASE ORDER QUOTE";
    doc.y = 110;
    doc.fontSize(14).fillColor(blue).text(typeLabel, { align: "center" });

    // Vendor info
    doc.y = 140;
    doc.fontSize(10).fillColor(grey).text("VENDOR");
    doc.fontSize(11).fillColor(black).text(vendor.shopName);
    doc.fontSize(9).fillColor(grey).text(vendor.location);
    doc.text(`WhatsApp: ${vendor.whatsappNumber}`);

    // Quotation meta
    doc.y = 140;
    const rightX = 350;
    doc.fontSize(10).fillColor(grey).text("TITLE", rightX, 140);
    doc.fontSize(11).fillColor(black).text(q.title, rightX);
    doc.fontSize(9).fillColor(grey)
      .text(`Status: ${q.status}`, rightX)
      .text(`Valid Until: ${q.validUntil ? new Date(q.validUntil).toLocaleDateString("en-IN") : "N/A"}`, rightX);

    // Line items table
    const tableTop = Math.max(doc.y, 230) + 20;
    doc.moveTo(50, tableTop - 4).lineTo(545, tableTop - 4).strokeColor("#d1d5db").stroke();

    // Table header
    doc.rect(50, tableTop - 4, 495, 18).fill(blue);
    doc.fontSize(9).fillColor("#ffffff");
    doc.text("#", 55, tableTop, { width: 20 });
    doc.text("Item Name", 75, tableTop, { width: 160 });
    doc.text("Description", 235, tableTop, { width: 120 });
    doc.text("Qty", 355, tableTop, { width: 40, align: "right" });
    doc.text("Unit", 395, tableTop, { width: 40 });
    doc.text("Unit Price", 435, tableTop, { width: 60, align: "right" });
    doc.text("Total", 495, tableTop, { width: 50, align: "right" });

    let rowY = tableTop + 20;
    let subtotal = 0;

    q.lineItems.forEach((item, idx) => {
      const rowH = 18;
      if (idx % 2 === 0) {
        doc.rect(50, rowY - 2, 495, rowH).fill(lightGrey);
      }
      const total = item.totalPrice ?? (item.quantity != null && item.unitPrice != null
        ? item.quantity * item.unitPrice : null);
      if (total != null) subtotal += total;

      doc.fontSize(9).fillColor(black);
      doc.text(String(idx + 1), 55, rowY, { width: 20 });
      doc.text(item.itemName, 75, rowY, { width: 160 });
      doc.text(item.description ?? "", 235, rowY, { width: 120 });
      doc.text(item.quantity != null ? String(item.quantity) : "", 355, rowY, { width: 40, align: "right" });
      doc.text(item.unit ?? "", 395, rowY, { width: 40 });
      doc.text(item.unitPrice != null ? `₹${item.unitPrice.toFixed(2)}` : "", 435, rowY, { width: 60, align: "right" });
      doc.text(total != null ? `₹${total.toFixed(2)}` : "", 495, rowY, { width: 50, align: "right" });

      rowY += rowH;
    });

    // Subtotal row
    rowY += 6;
    doc.moveTo(50, rowY).lineTo(545, rowY).strokeColor("#d1d5db").stroke();
    rowY += 6;
    doc.fontSize(10).fillColor(black)
      .text("SUBTOTAL", 400, rowY, { width: 95, align: "right" })
      .text(`₹${subtotal.toFixed(2)}`, 495, rowY, { width: 50, align: "right" });

    // Notes
    if (q.notes) {
      rowY += 30;
      doc.fontSize(9).fillColor(grey).text("NOTES", 50, rowY);
      doc.fontSize(9).fillColor(black).text(q.notes, 50, rowY + 14, { width: 495 });
    }

    // Footer
    doc.fontSize(8).fillColor(grey)
      .text("Generated by Fulfilus Vendor Intelligence Platform", 50, 780, { align: "center", width: 495 });
  }
}
